Repository YAPP-Github/20th-Web-Team-2-BE, pull requests merged in 2022-06, with the labels that each got.

#6 Feat/email - 이메일 전송, 인증코드 검사 구현 완료
  user-service/src/main/java/com/isloand/userservice/controller/UserController.java
  user-service/src/main/java/com/isloand/userservice/dto/AuthCodeRequest.java
  user-service/src/main/java/com/isloand/userservice/dto/AuthCodeResponse.java
  user-service/src/main/java/com/isloand/userservice/entity/EmailTokenEntity.java
  user-service/src/main/java/com/isloand/userservice/entity/User.java
  user-service/src/main/java/com/isloand/userservice/entity/UserEntity.java
  user-service/src/main/java/com/isloand/userservice/repository/UserRepository.java
  user-service/src/main/java/com/isloand/userservice/service/EmailService.java
  user-service/src/main/java/com/isloand/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
Labels: enhancement

#10 [Feature/setting] : Spring MSA 환경 설정
  discovery-service/src/main/java/com/isloand/discoveryservice/DiscoveryServiceApplication.java
  discovery-service/src/main/resources/application.properties
  discovery-service/src/main/resources/application.yml
  gateway-service/pom.xml
  gateway-service/src/main/resources/application.properties
  gateway-service/src/main/resources/application.yml
  user-service/pom.xml
  user-service/src/main/java/com/isloand/userservice/UserServiceApplication.java
  user-service/src/main/java/com/isloand/userservice/entity/UniversityEntity.java
  user-service/src/main/resources/application.yml
Labels: enhancement

#17 [feat] : 엔티티 정의
  lonessum/src/main/java/com/yapp/lonessum/domain/constant/Characteristic.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/CreateSurveyReq.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/EmailTokenEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/resources/application.yml
Labels: enhancement

#24 meeting matching algorithm 구현
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MatchingInfo.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingScore.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingSurveyDto.java
  lonessum/src/test/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithmTest.java
  lonessum/src/test/java/com/yapp/lonessum/domain/meeting/utils/testDataFactory.java
Labels: enhancement

#21 [feat] : @RestControllerAdvice를 이용한 예외처리
  lonessum/src/main/java/com/yapp/lonessum/domain/constant/Character.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/CommonErrorCode.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/ErrorCode.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
  lonessum/src/main/java/com/yapp/lonessum/exception/exception/RestApiException.java
  lonessum/src/main/java/com/yapp/lonessum/exception/handler/GlobalExceptionHandler.java
  lonessum/src/main/java/com/yapp/lonessum/exception/response/ErrorResponse.java
Labels: enhancement

#25 [feat] : Mapstruct와 연동해서 설문 CRUD API 작성
  lonessum/pom.xml
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/ReadSurveyRes.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/UpdateSurveyReq.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/mapper/GenericMapper.java
  lonessum/src/main/java/com/yapp/lonessum/mapper/MeetingSurveyMapper.java
Labels: enhancement

#30 [fix] : api response 자료형 변경 및 컨트롤러 url 변경
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
Labels: fix

#31 [feat] : 소개팅 설문 CRUD API 생성
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/repository/DatingSurveyRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/mapper/DatingSurveyMapper.java
Labels: enhancement

#32 Feature/dating - dating 관련 알고리즘 구현 및 공통화 작업
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/AlgorithmUtil.java
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingInfo.java
  lonessum/src/main/java/com/yapp/lonessum/common/dto/SurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/algorithm/DatingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/algorithm/DatingScore.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingScore.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingSurveyDto.java
  lonessum/src/test/java/com/yapp/lonessum/domain/dating/algorithm/DatingMatchingAlgorithmTest.java
  lonessum/src/test/java/com/yapp/lonessum/domain/dating/utils/testDataFactory.java
  lonessum/src/test/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithmTest.java
  lonessum/src/test/java/com/yapp/lonessum/domain/meeting/utils/testDataFactory.java
Labels: enhancement

#33 [feat] : 이메일 유효성 검사
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/repository/UniversityRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: enhancement

#36 [feat] : 카카오 로그인 시 회원가입, 토큰에서 유저정보 가져오기
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/repository/UserRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: enhancement

#37 [fix] : 서비스 간 순환 참조 해소, 이메일 검사 정규식 테스트
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UserController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
  lonessum/src/test/java/com/yapp/lonessum/domain/user/service/EmailServiceTest.java
Labels: fix, test
