Repository YAPP-Github/20th-Web-Team-2-BE, pull requests merged in 2022-07, with the labels that each got.

#43 [feat] : 유저 <-> 설문 비즈니스 로직 변경, 매칭 스케줄링 구현
  lonessum/src/main/java/com/yapp/lonessum/LonessumApplication.java
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingInfo.java
  lonessum/src/main/java/com/yapp/lonessum/config/SwaggerConfig.java
  lonessum/src/main/java/com/yapp/lonessum/domain/constant/MatchStatus.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/repository/DatingMatchingRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/repository/DatingSurveyRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/repository/MeetingMatchingRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/repository/MeetingSurveyRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/SurveyErrorCode.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: enhancement, fix

#48 [feat] : 지원하는 대학 리스트 조회
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UniversityController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/UniversityDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
Labels: enhancement

#50 [feat] : OAuth로 유저 나이정보 받아오기, 설문 작성 시 나이 검사
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: enhancement

#58 매칭 알고리즘 필수 조건 추가
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/algorithm/DatingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithm.java
Labels: fix

#59 [feat] : 페이플 결제 테스트 API
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/client/PaypleFeignConfig.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/client/PayplePartnerAuthClient.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/client/PayplePaymentCertClient.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/controller/PaymentController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/dto/PayplePartnerAuthRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/dto/PayplePartnerAuthResponse.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/dto/PayplePaymentCertRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/dto/PayplePaymentCertResponse.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/dto/PayplePaymentResultResponse.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/entity/MatchType.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/entity/Payment.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/repository/PaymentRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/service/PaymentService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/SurveyErrorCode.java
Labels: enhancement

#62 지역정보 등록 및 조회 api 생성
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/AbroadAreaController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UniversityController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UserController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/AbroadAreaDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/AbroadAreaEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/repository/AbroadAreaRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
  lonessum/src/main/resources/university/city_info.csv
Labels: enhancement

#66 [feat] : 테스트용 회원가입,로그인 작성, jwt 인증 구현
  lonessum/pom.xml
  lonessum/src/main/java/com/yapp/lonessum/config/WebMvcConfig.java
  lonessum/src/main/java/com/yapp/lonessum/config/jwt/JwtInterceptor.java
  lonessum/src/main/java/com/yapp/lonessum/config/jwt/JwtService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/controller/PaymentController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UserController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/EmailRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/JoinRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/LoginRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/LoginResponse.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/repository/UserRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: enhancement

#67 [fix] : 유저와 설문 연관관계 수정에 따른 로직 수정
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
Labels: fix

#65 [feat] : 매칭 상태 및 결과 조회 API
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingInfo.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingPartnerSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingPartnerSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/SurveyErrorCode.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: enhancement

#68 [fix] : Jwt 인터셉터 예외경로 추가
  lonessum/src/main/java/com/yapp/lonessum/config/WebMvcConfig.java
Labels: fix

#71 [fix] : 카카오 로그인 시 jwt 토큰 반환
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: fix

#72 [feat] : 로컬, 배포 서버 DB 환경 분리
  lonessum/src/main/resources/application-prod.yml
  lonessum/src/main/resources/application.yml
Labels: enhancement

#73 [fix] : Mysql 의존성 추가
  lonessum/pom.xml
Labels: fix

#76 [fix] : 소개팅 설문의 myUniversity 정보 저장
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingSurveyService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: fix

#77 [fix] : Jwt 토큰에 대한 CORS Preflight 에러 처리
  lonessum/src/main/java/com/yapp/lonessum/config/WebMvcConfig.java
  lonessum/src/main/java/com/yapp/lonessum/config/jwt/JwtInterceptor.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/AbroadAreaController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UniversityController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UserController.java
Labels: fix

#82 [test] : 배포 환경에서 SMTP 동작 여부를 확인
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: test

#83 [test] : 배포 환경에서 SMTP 동작 여부를 확인
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: test

#86 logback 설정 추가
  lonessum/pom.xml
  lonessum/src/main/resources/application-prod.yml
  lonessum/src/main/resources/application.yml
  lonessum/src/main/resources/logback-prod.xml
  lonessum/src/main/resources/logback.xml
Labels: enhancement

#89 [fix] : 설문 수정하기 PUT -> PATCH
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
Labels: fix

#93 [fix] : 유저 로그인 시 필요 정보 반환
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/LoginResponse.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: fix

#94 [fix] : 이미 설문이 있을 때 설문 생성 시 오류
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingSurveyService.java
Labels: fix

#96 [test] : 배포 서버 이메일 전송 테스트
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
Labels: test

#87 admin filter 적용
  lonessum/src/main/java/com/yapp/lonessum/common/filter/AdminFilter.java
  lonessum/src/main/java/com/yapp/lonessum/config/WebConfig.java
Labels: enhancement

#95 랜덤 매칭 알고리즘 구현
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/common/dto/SurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/algorithm/DatingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/algorithm/RandomDatingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingSurveyDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/MeetingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/algorithm/RandomMeetingMatchingAlgorithm.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingSurveyDto.java
Labels: enhancement

#98 [fix] : jwt 인증 정리
  lonessum/src/main/java/com/yapp/lonessum/config/SwaggerConfig.java
  lonessum/src/main/java/com/yapp/lonessum/config/WebMvcConfig.java
  lonessum/src/main/java/com/yapp/lonessum/config/jwt/JwtInterceptor.java
  lonessum/src/main/java/com/yapp/lonessum/config/jwt/JwtService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingSurveyController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/controller/PaymentController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: fix

#101 [feat] : Thymeleaf를 이용해 html 파일 이메일 전송
  lonessum/pom.xml
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/controller/EmailController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/dto/EmailRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/dto/TestEmailRequest.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/entity/EmailTokenEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/repository/EmailTokenRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/repository/AbroadAreaRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/java/com/yapp/lonessum/utils/AuthCodeGenerator.java
  lonessum/src/main/resources/templates/AuthCode.html
  lonessum/src/main/resources/templates/MatchResult.html
Labels: enhancement

#102 [fix] : 이메일 전송용 html 이미지 src 수정
  lonessum/src/main/resources/templates/AuthCode.html
  lonessum/src/main/resources/templates/MatchResult.html
Labels: fix

#103 [fix] : 이메일 인증 토큰을 Redis에 저장
  lonessum/src/main/java/com/yapp/lonessum/domain/email/entity/EmailToken.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/entity/EmailTokenEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/repository/EmailTokenRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/service/EmailTokenService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/UserErrorCode.java
Labels: enhancement, fix

#104 [fix] : 매칭 결과 반환 시 매칭 결제 마감일 포함
  lonessum/src/main/java/com/yapp/lonessum/common/algorithm/MatchingInfo.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/controller/DatingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/TestDatingMatchingResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/controller/MeetingMatchingController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/TestMeetingMatchingResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
Labels: enhancement

#106 [fix] : 매칭 생성 후 설문 상태 수정
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/AbroadAreaController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
Labels: fix

#108 [feat] : 다음날까지 결제하지 않은 유저는 FAILED 상태로 변한다
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/exception/errorcode/SurveyErrorCode.java
Labels: enhancement

#109 [fix] : 유저 나이 정보 받아오기
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: fix

#114 [feat] : Application 시작 시 대학정보, 지역정보 자동 등록
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
  lonessum/src/main/resources/university/university_info.csv
Labels: enhancement

#115 [fix] : MatchStatus의 상태 수정
  lonessum/src/main/java/com/yapp/lonessum/domain/constant/MatchStatus.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
Labels: fix

#116 [fix] : 배포 서버에서 대학,지역정보 자동 등록 주석처리
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
Labels: fix

#121 [feat] : 유저 프로필 조회 API
  lonessum/src/main/java/com/yapp/lonessum/domain/constant/MatchStatus.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/OAuthController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/controller/UserController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/dto/UserInfoDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/AbroadAreaService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UniversityService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/resources/university/university_info.csv
Labels: enhancement

#123 [fix] : 테스트용 이메일 도메인 자동 추가
  lonessum/src/main/java/com/yapp/lonessum/domain/abroadArea/AbroadAreaController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/abroadArea/AbroadAreaDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/abroadArea/AbroadAreaEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/abroadArea/AbroadAreaRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/abroadArea/AbroadAreaService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/email/service/EmailService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/university/UniversityController.java
  lonessum/src/main/java/com/yapp/lonessum/domain/university/UniversityDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/university/UniversityEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/university/UniversityRepository.java
  lonessum/src/main/java/com/yapp/lonessum/domain/university/UniversityService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/entity/UserEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
  lonessum/src/main/resources/application-prod.yml
Labels: fix

#127 [feat] : 관리자의 결제 확인 처리 기능
  lonessum/src/main/java/com/yapp/lonessum/domain/admin/AdminService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/entity/DatingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/scheduler/DatingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingMatchingEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/entity/MeetingSurveyEntity.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/scheduler/MeetingMatchingScheduler.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/entity/Payment.java
  lonessum/src/main/java/com/yapp/lonessum/domain/payment/service/PaymentService.java
Labels: enhancement

#128 [fix] : 테스트 유저는 인증 없이 설문 생성 가능
  lonessum/src/main/java/com/yapp/lonessum/domain/user/service/UserService.java
Labels: fix

#129 [fix] : 매칭이 결제 대기 상태일 때 입금자명 포함해서 응답
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/dto/DatingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/dating/service/DatingMatchingService.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/dto/MeetingMatchResultDto.java
  lonessum/src/main/java/com/yapp/lonessum/domain/meeting/service/MeetingMatchingService.java
Labels: fix
